### ISSUE TITLE
Publish to Brackets extension registry

### ISSUE THREAD

**Issue by petetnt** [brackets-userland/brackets-sass-lint#1]
[Due to an on-going issue with `brackets-registry`](https://github.com/adobe/brackets/issues/7387), this package is only available on [`brackets-npm-registry`](https://github.com/zaggino/brackets-npm-registry).

When the issue is resolved the extension can be installed from the regular Extension Registry too.

**Comment by glen-84** [comment]
What about excluding sass-lint, and loading it from either the project's node_modules, or the user's global installation of sass-lint?

**Comment by petetnt** [comment]
@glen-84 Both are good options with some drawbacks, the `node_modules` approach is basically what `brackets-npm-registry` does for us currently. The optimal case would be Brackets allowing `npm install`s for the the extensions but I don't think that will happen anytime soon.

The global installation would be another option, but I'd like this to work out of the box. As a workaround I could publish a version on the `Brackets Registry` that depends on globally installed `sass-lint`, that sounds good to me.  👍

**Comment by glen-84** [comment]
I don't really follow what you're saying about `brackets-npm-registry` – with the first option I meant using the sass-lint version that a user may have installed locally inside their project. Linter extensions like [vscode-tslint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) for VS Code do this – if tslint is installed locally, it is used, otherwise the global installation is used.

The linting library is not included with the extension, which also means that it can be updated separately by the user.

**Comment by petetnt** [comment]
@glen-84 Oh yeah that makes sense, the flow should be `installed by extension || installed locally in project || installed globally`.

I'll work on that soon-ish.

**Comment by alvint** [comment]
Hi, the referenced registry issue has been resolved.

**Comment by petetnt** [comment]
Thanks for informing @alvint, I'll test and merge #6 today and I try releasing one to the registry later today!

**Comment by petetnt** [comment]
The extension is now published to extension registry!

**Comment by alvint** [comment]
Cool!
